### ISSUE TITLE
ReferenceError: React is not defined on basic usage

### ISSUE THREAD

**Issue by alessandro-bottamedi** [jonsamp/react-native-fade#2]
Hi, when I try to use react-native-fade I get the error `ReferenceError: React is not defined`.

i am using `react-native-fade 2.0.1`, `expo bare 36.0 (RN 0.61.4)` and `react-native-reanimated 1.4.0`

I tried to copy the source code from github directly to a file in my app and, importing it instead of node_modules, everything works correctly.

**Comment by jonsamp** [comment]
Thanks for this issue. Sorry for the late response. I just pushed an update to this library to make it a better package. Now you should be able to install this project in an Expo project and not receive that error.
