### ISSUE TITLE
Multiple <Fade> components don't have own animated values

### ISSUE THREAD

**Issue by rikkitissier** [jonsamp/react-native-fade#5]
In my usecase I have more than one Fade on the screen (one is shown when the other is hidden), but right now they share the same visibility (i.e. they both appear or both hide, at the same time). I think this is probably because the opacity is being set as a module-level const rather than a component-level property, but I haven't tested that yet.

Thanks for the handy little Fade component!

**Comment by boicoder** [comment]
@rikkitissier Hello, i also have this problem was there any solutions?

**Comment by jonsamp** [comment]
This is now fixed with this commit/change: https://github.com/jonsamp/react-native-fade/blob/b13f64944d57eef77bc51897962048fe7e5fb079/src/index.tsx

https://user-images.githubusercontent.com/6455018/136334405-349fa4c9-bc41-4e00-9f9a-699961af24b9.mov

Thanks for reporting!
